### ISSUE TITLE
[Feature request] SublimeTail support

### ISSUE THREAD

**Issue by Kristinita** [poucotm/Log-Highlight#1]
### Summary

It would be nice, if you add SublimeTail support.

### Expected behavior

Highlight SublimeTail logs.

### Actual behavior

If tab with Tail was opened for me, <kbd>Ctrl+Shift+P</kbd> → `LogHighlight: Highlight Error/Warning` → <kbd>Enter</kbd> → Tail log not highlight for me, I get message in status bar:

    Unknown name for current view

### Steps to reproduce

I install [SublimeTail](https://github.com/vifo/SublimeTail/tree/devel) → I open log file → `Tail: Tail File In New View` → Tail tab open for me. 

![Tail Tab](http://i.imgur.com/Iqkd0Ga.png)

I change log file → I see changes in Tail tab. If I try highlight log in Tail tab, I get actual behavior.

### Not helped

My `User\Log Highlight.sublime-settings` file:

```json
{
    "log_ext": [ ".log", "Tail" ],
}
```

But I still get actual behavior.

Thanks.

**Comment by poucotm** [comment]
Hi, Kristina
The reason of "Unknown ..." is that "Tail: chol..." is unsaved. Try to do again after saving. But it can be not good solution. What is "Sublime Tail"?

**Comment by Kristinita** [comment]
@poucotm, [**SublimeTail**](https://github.com/vifo/SublimeTail/tree/devel) is package for working with logs. See [**Tail (Unix)**](https://en.wikipedia.org/wiki/Tail_(Unix)). If I have big log, I can see only last log changes. Example of work:

![SublimeTail](http://i.imgur.com/PBw4jiZ.gif)

> Try to do again after saving.

If I save file, SublimeTail not will work. It would be nice, if Log-Highlight will be highlight unsaved files too.

Thanks.

**Comment by poucotm** [comment]
Hi, Kristina.
I've updated Log-Highlight to support unsaved file like 'Sublime Tail'.
But you also have to add some codes in Sublime Tail. Or request it.
In order to search base directories (to use links),  "absolute file path" is needed.
It is impossible to get a path from a unsaved file. But for 'Sublime Tail' you can set the file path as a setting of view. Add the codes like the following :

In "Tail/packages/tail/commands/tail_file_in_new_view.py"
        ...
        sublime_view = self.view.window().new_file()
        tail_view = get_tail_view(sublime_view=sublime_view, create=True)
        tail_view.add_source(get_tail_source(filepath=filename))
        tail_view.start()
        **sublime_view.settings().set('filepath', filename)**

**Comment by Kristinita** [comment]
@poucotm, I add 

```python
sublime_view.settings().set('filepath', filename)
```

in last line of `Tail/packages/tail/commands/tail_file_in_new_view.py`, but I get same error.

> You have to click a link in 'Summary View' for first time or change view once to use links.

I'm sorry, where I can find `Summary View`?

Thanks.

**Comment by poucotm** [comment]
Did you check the version of Log Highlight?
It also has to be updated as 0.6.5.
When you run Log Highlight, Summary View will be displayed bottom of the window as default.

**Comment by Kristinita** [comment]
@poucotm, may you write step-by-step, what I need to make to have expected behavior? I can not understand, how I can get expected behavior.

Thanks.

**Comment by poucotm** [comment]
1. add the codes

![tail1](https://cloud.githubusercontent.com/assets/19210389/21471807/21b44c32-cb02-11e6-8d8b-d1d8ed41e1ce.png)

2. open the log and run "Tail: File In New View"

![tail2](https://cloud.githubusercontent.com/assets/19210389/21471812/4a874646-cb02-11e6-83ad-dcd9da710a58.png)

3. run "Log Highlight" for tailed Log

![tail4](https://cloud.githubusercontent.com/assets/19210389/21471815/5ffa07de-cb02-11e6-9ae8-c55883afccae.png)

4. The first View before log updated

![tail5](https://cloud.githubusercontent.com/assets/19210389/21471817/8911182e-cb02-11e6-97e1-584ba16124a9.png)

5. When the log contents changed, you can see updated in tailed log view

![tail6](https://cloud.githubusercontent.com/assets/19210389/21471825/ac511f8c-cb02-11e6-8591-f9629ab14c07.png)

**Comment by Kristinita** [comment]
Thank you very much!

**Comment by poucotm** [comment]
Hi, Kristinita
I've changed workaround for ST3 bug in v0.8.0. You can use links in Tail view directly without Summary View.
