### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by gituser823** [poucotm/Log-Highlight#11]
Hello,

I configured the use of icons, but it does not show any icons in sublime.
Highlighting the Lines works fine.

I tried everything: icon, dot and circle all dont show any icons.
I tried Danish Royalty/warning.png and Danish Royalty/error.png as well as no image at all.

Somehow I was able to see Icons some time ago once, but I dont remember doing anything specific to enable them.

Using LogHighlight 1.8.5 and Sublime 3.0, build 3143 on a Linux Mint 18.1 Cinnamon and Kernel 4.4.0-104

**Comment by poucotm** [comment]
Hi,
Didn't you see any icons at first ? If that case, it doesn't look like the
package problem.
If you don't see after changing settings, please, show your settings.



2018-01-11 18:52 GMT+09:00 gituser823 <notifications@github.com>:

**Comment by gituser823** [comment]
I don't remember really, but I don't think I saw the Icons at start.
Can you tell me the Path where Danish Royalty/warning.png and Danish Royalty/error.png should be?

config:

`{

	/*  Configuration  ____________________________________________
	*/

	// enable context menu
	"context_menu": true,

	// Auto Highlight for a log file, build window
	"auto_highlight" : true,

	// log file extension
	"log_ext": [ ".log"  ], // use ".*" for all file extensions - but can not use `Auto Highlight`

	// "compile" - link, summary, bookmark are usable, "system" - only for highlight
	"log_type": "system",

	/*  Options for `compile` type log  ___________________________
	*/

	// use clickable link or not
	"use_link": false,

	// search base directory automatically for relative path
	"search_base": {
		"enable" : true,
		// hidden folders are ignored as default, like .git, .svn
		"ignore_dir" : [""],
		// adjust when using network like samba
		"max_scan_path" : 1000
	},

	// summary panel
	"summary_panel": false,         // show summary panel

	// bookmark
	"bookmark_enable": true,       // enable/disable bookmarks
	"bookmark_goto_error": true,   // automatically go to 1st error line

	/*  Log Syntax, Color scheme  _________________________________
	*/

	// severity level
	"severity" : {


		// error red__________________________________________________
		"error" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^Error-\\[", "^\\s*[\\n]" ],                      // Error-[ ~ next empty line (multi-line)
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)error", "[\\r\\n]" ],  // a line including case-insensitive 'error' with or without a link in front of 'error'
				[ "^\\w+:\\s*\\*E", "[\\r\\n]" ],                     // ...: *E ... (single line)
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)memtest failed", "[\\r\\n]" ],
				[ "^Warning-\\[", "^\\s*[\\n]" ],                    // Warning-[ ~ next empty line (multi-line)
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)warning", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or without a link in front of 'warning'
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)failed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)fail", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?\\[err\\]", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)DRDY ERR", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)invoked oom-killer", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Call Trace:", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?syno_poweroff_task", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?syno_poweroff_task", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ext4-fs error", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?disabled", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?JBD2: Error", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)<[a-zA-Z0-9]{16}>", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF0000", // error message
				"link"  : "#E6DB74", // link in error message
				"quote" : "#4F99D3"  // quote in error message
			},
			"dot"  : "Danish Royalty/error.png"   // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// error light red________________________________________________
		"lighterror" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*? updater: ", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF7F7F", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			"dot"  : "Danish Royalty/error.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// okay green________________________________________________
		"warning" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^\\w+:\\s*\\*W", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*? is ok!!", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Successfully started ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?finished boot up", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?enabled", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)memtest passed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Success to update", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Startup successful", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?all service finish boot up", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#A1B347", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			"dot"  : "Danish Royalty/warning.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// kernel blue________________________________________________
		"kernel" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				//[ "^{{{LINK}}}?[^\\r\\n]*?(?i)kernel: \\[", "[\\r\\n]" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?init: ", "[\\r\\n]" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?([0-9]{1,6})\\.([0-9]){6}", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#33B5E5", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			"dot"  : "Danish Royalty/error.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// yellow info________________________________________________
		"yellow_info" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)none yet", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or without a link in front of 'warning'
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)no other find", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or without a link in front of 'warning'
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)hotplugd:", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF9900", // yellow info message
				"link"  : "#FF9900", // link in yellow info message
				"quote" : "#FF9900"  // quote in ywllow info message
			},
			"dot"  : "Danish Royalty/warning.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		/*// to be decided________________________________________________
		"dark_blue" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				[ "^{{{LINK}}}?[^\\r\\n]*?img_backup: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*? upsmon", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*? upsd", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?root: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?updater-svr: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synocheckshare: ", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#9d15f6", // yellow info message
				"link"  : "#9d15f6", // link in yellow info message
				"quote" : "#9d15f6"  // quote in ywllow info message
			},
			"icon"  : "Danish Royalty/warning.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},*/

		// to ignore grey ________________________________________________
		"greyed" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)link is slow to respond, please be patient", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)wake up successful, the reset fail can be ignored", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)wake up from deepsleep, reset link now", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)times, suppressed by syslog-ng on", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)device unplugged sstatus", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)synopkgctl: resource_api.cpp:163 Acquire", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)synoscgi_SYNO.Core.Package.Uninstallation_1_uninstall", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)synoscgi_SYNO.Core.Package.Installation_1_install", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i) is not ssd", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?] info cache generated", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?System isn't ready, so cannot get scemd status.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?thumbd: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?RCClean succeeded", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?root: Check device busy: passed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?mkcert: Verifying certificate in", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synopkg: resource_api.cpp:", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synodrnode: Clear temp credential of DRNode", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synoscgi_SYNO.Photo.Thumbnail_1_get", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Job pkg-LogCenter-syslog is not running, skip reload service action", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synoscgi_SYNO.Core.Package.Control_1_stop", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?scanner.c:1413 skip counting", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?DDNS Expired. UpdateAll.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?DDNS got IP changed. UpdateAll.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synologrotated: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synoavscan: scanner.c:1861 skip scan", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?not factory enviroment, finish manutild", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synocrtregister: synocrtregister.cpp:162 Register certificate for", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synoavscan: synoav_engine.c:120 Initialize engine with", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?device plugged sstatus", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#71878F", // greyed out message
				"link"  : "#71878F", // link in grey message
				"quote" : "#71878F"  // quote in grey message
			},
			"dot"  : "Danish Royalty/error.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// orange network ___________________________________________________
		"network" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?gateway_change hook event: ", "[\\r\\n]" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?ipv4_change hook event: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?dhcp-client: ", "[\\r\\n]" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?if_link_up hook event: ", "[\\r\\n]" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?if_link_down hook event: ", "[\\r\\n]" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?dns_change hook event: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?dns_config_change", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?interface-catcher: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(ipv6_change|ipv4_change|if_link_up|if_link_down|dns_change) hook event", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?gateway_config_change hook event: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?dhcp-client6: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synonetd: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ipsec_", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synonet: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?synonet: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ntpd", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF8E5A", // info message
				"link"  : "#b36915", // link in info message
				"quote" : "#428a99"  // quote in info message
			},
			"dot"  : "Danish Royalty/error.png"    // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		}

		// <-- Remove, Change, Add More Severity Level Here -->
	},

	// theme color set
	"theme_color": {
		"background"      : "#161C23",
		"foreground"      : "#D7D7D7",
		"caret"           : "#F29718",
		"selection"       : "#3A5166",
		"selectionBorder" : "#181E26",
		"lineHighlight"   : "#283240",
		"summary_title"   : "#D7D7D7"
	}

}
`

**Comment by poucotm** [comment]
You set "log_type": "system" in settings. It disables bookmarking with icons. And "dot" should be "icon" to use icons. 
Try to do again after change above.
"log_type": "system" is for fast and light operation.

**Comment by gituser823** [comment]
Okay thank you, that worked.

Is it possible to add and use custom added icons?
If so, where do i have to put them?

**Comment by poucotm** [comment]
Try to put them in 'Packages/Log Highlight/icons'

**Comment by gituser823** [comment]
The Folders Log Hightlight and icons did not exist, so I created them and put an icon in there.
But it is not displayed. I can only see an orange bugged icon.
I guess this is the wrong Folder? I copied it to /home/thomas/.config/sublime-text-3/Packages/Log Highlight/icons

**Comment by poucotm** [comment]
The path looks correct. In my test, it works.

Use Preference > Browse Package and check whether it is correct.

2018. 1. 12. 오후 10:49에 "gituser823" <notifications@github.com>님이 작성:

**Comment by poucotm** [comment]
You can each file in the package here. https://github.com/poucotm/Log-Highlight
Not to use an icon , just remove the line "icon": ...
