### ISSUE TITLE
Feature req colored icons

### ISSUE THREAD

**Issue by tablatronix** [poucotm/Log-Highlight#14]
It would be nice if the circle dots were colored to `base` or custom `color[n]` , fallback to a theme_color attribute etc.

Like how git gutter looks

**Comment by tablatronix** [comment]
```py
			],
			"color" : {
				"base"  : "#70991f", // info message
				"link"  : "#b36915", // link in info message
				"quote" : "#428a99"  // quote in info message
				"icon"  : "#F6F6F6"  // icon (non image) in info message
			},
			"icon"  : "circle"    // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		}
```

**Comment by poucotm** [comment]
You can customize icons as you want by overriding package. Make the folder Packages/Log Highlight/icons, put your icons and change icon settings like - foor/bar.png.
I think it will be better.

**Comment by tablatronix** [comment]
I think gitgutter uses white icons, and somehow colorizes them, this lets them be themed.
Not exactly sure how it works, I will dig deeper.

**Comment by poucotm** [comment]
I've added that in v1.8.7.
