### ISSUE TITLE
capture groups coloring?

### ISSUE THREAD

**Issue by tablatronix** [poucotm/Log-Highlight#15]
I thought I would be able to color by capture group, but it seems it only has quotes and url which I assume is hard coded? why not add these as capture groups in the regex?

how would I color code key value pairs? I see how I can color the whole line, or half. but not both. Am i wrong?

```
Mode: STA
PHY mode: N
Channel: 1
AP id: 0
Status: 1
```

also could use lookaheads to leave delimiters as default color or something else, hmm

**Comment by poucotm** [comment]
The package was made to highlight something special pattern for a log. As you commented, quotes and links patterns are hard coded in general. To highlight separately above pattern by using Log Highlight, you have to define two separate regex - one for xxx:, another for :xxx.

**Comment by tablatronix** [comment]
So create 2 severity levels and customize colors there?
I have only been able to color an entire line one color, is there a way to only color part of a group match only ?

**Comment by tablatronix** [comment]
ohhhhhh
` [ "match regex", "" ]`

doh!

**Comment by tablatronix** [comment]
This is satisfactory, I will close, but I still think even more capture groups per level would be easier to maintain, making this much more powerful for debug logs and build systems.
