### ISSUE TITLE
Broken relative path with current version v1.8.7

### ISSUE THREAD

**Issue by StudioDanton** [poucotm/Log-Highlight#18]
Hi,
Same issue as before (#10), seems to came back in version v1.8.7
When I parse and open log file with relative path like :
../../../ast/src/drivers/src_unit/man/TU_data_man.cpp:1091: failed: ...
instead of opening TU_data_man.cpp, it open a new empty file without taking car of ../../../ and I get this in the console :
File "Log Highlight in \Sublime Text 3\Installed Packages\Log Highlight.sublime-package", line 850, in search_base
File "./python3.3/ntpath.py", line 113, in join
File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()

Thank you by advance for investigating this regression.

**Comment by poucotm** [comment]
I cannot reproduce your error. I just change something by guessing. please, check w/ v.1.8.8

**Comment by StudioDanton** [comment]
Hi,
I've just upgraded your plugins to version 1.8.8 and it's working properly now !

Thank you for your very quick fix.
