### ISSUE TITLE
Define new pattern set

### ISSUE THREAD

**Issue by giaplv57** [poucotm/Log-Highlight#2]
Hi Poucotm,

Firstly, such an awesome package! 
I wonder can I define a new pattern set, for example:
**"info_pattern": [
	[ "\\[INFO\\]", "\\n" ], 
],**
and then choose the color for this type of pattern set?
Also, in some big log file, the "Bookmarks" and "Go To Position" make sublime very lag. Can I have an option to turn off these feature for big log file?

Thanks very much!
Giap

**Comment by poucotm** [comment]
Hi Giap,

I've added `info` pattern and bookmark enable options.
Please, check v0.7.0 with its README

Best Regards,
Kris

**Comment by giaplv57** [comment]
Hi Poucotm,
The info pattern seem not work in my case. Here is my user setting:
![capture](https://cloud.githubusercontent.com/assets/6805551/21707858/8c95c4ca-d405-11e6-8d71-cad0364c6f0e.PNG)
And here is my log file after highlighted:
![capture](https://cloud.githubusercontent.com/assets/6805551/21707901/1fe2287c-d406-11e6-814e-9e7e59f75983.PNG)
You can see that the INFO line is not highlighted. 
Also, although that the bookmark is set to false, when I tell the Log Highlight to highlight my text, it still running finding something (in this case, I just want it highlight the text for me, and not anything more)
Can you check for me, please?

Thank,
Giap

**Comment by poucotm** [comment]
Hi, Giap,

For INFO pattern, it looks working well with your settings. I don't know
the reason. Did you try to re-run sublime-text ?

[image: 본문 이미지 1]

The process which you have seen something is searching base directory of
relative path link. Do you want to turn off that also ?
If then, you can not go to link for relative path when you double-click it.

Best Regards,
Kris.




2017-01-06 13:52 GMT+09:00 giaplv57 <notifications@github.com>:
