### ISSUE TITLE
Map server path to client path

### ISSUE THREAD

**Issue by jancbeck** [poucotm/Log-Highlight#23]
I'm running a development server within a Vagrant VM. 
Clicking the blow link will take me to a directory that does not exist on my local client, but within the VM.

`[31-Mar-2018 19:09:41 UTC] PHP Notice:  Undefined property: stdClass::$plugin in /srv/www/example/htdocs/wp-includes/class-wp-list-util.php on line 150`

It would be great to be able to map these remote paths to my local dev directory.

```
"path_mapping": {
       "/srv/www/example" : "/Users/jan/vvv/www/example"
}
```

**Comment by jancbeck** [comment]
Ok, turned out that popup doesn't match the files the way I want it. It will look at the content of the current project and try to guess which file I'd want based on its contents rather than take the literal file referenced in the log file.

This ended up bugging me enough that I wrote a short gulp task for it that watches a given log file and replaces the server path with my local path.

[Gist here](https://gist.github.com/jancbeck/903fc7ca305703a929590fc7a546bc9f)

**Comment by robrecord** [comment]
I created /srv in my root, and a symlink www inside it that points to my ~/Sites dir. Inside the site directory (eg 'cea' or 'mywebsite.com') I created another symlink to go to the correct folder - it looks like you might not need this, but mine was current -> site. 

This allowed me to open the files referenced by the log.

**Comment by robrecord** [comment]
I know you've done a lot of work on setting up the base_dir for log files, @poucotm - (thank you) - although there is still this use case that needs addressing. If you use a virtual machine then you get a path in the log that is different than on your host machine.

If there was an option configurable in the project settings that could map the beginning of the path to the project's path, that might solve the issue.

Eg. for vagrant:

My file with errors might show up in the log as:
**/srv/www/mywebsite.com/current**/web/app/themes/mytheme/functions.php

The real path in my host machine might be:
**/Users/MyUser/Sites/mywebsite.com/site**/web/app/themes/mytheme/functions.php

So the mapping would need to look something like:
    "map_path": {
        [
            "/srv/www/mywebsite.com/current",
            "/Users/MyUser/Sites/mywebsite.com/site"
        ]
    }

**Comment by jancbeck** [comment]
I'm currently also working with the workaround that @robrecord describes. The downside of this is that Sublime treats the files under my /srv symlink as different files than the ones in my project. That's OK if I just want to quickly jump into a class or function referenced by the log and see what is going on there, but of course it would be much better if this would not open a new file tab.

**Comment by poucotm** [comment]
@jancbeck , Currently, it looks impossible to change a path mapping, because the package uses `result_file_regex` . It is just one of view settings. The way is to change the mechanism calling a link file instead of `result_file_regex`.
