### ISSUE TITLE
Set different Severy Levels/ Highlight for different Filetypes

### ISSUE THREAD

**Issue by gituser823** [poucotm/Log-Highlight#25]
Hello,

can you implement, that I can add different highlights/severity levels for different files or different file types?
Or this already possible somhow?
Couldn't find anything about it.

Sure, I can set *.extension, but I would like to set different filetypes, or different full-filenames for different defined severity levels.

Thanks, love your Mod so far!

**Comment by poucotm** [comment]
@gituser823 , Hi, I've updated v2.0.0. Now it supoorts multiple kinds of logs.
