### ISSUE TITLE
Sidebar not opened if AutoHighlight is enabled

### ISSUE THREAD

**Issue by gituser823** [poucotm/Log-Highlight#26]
Hello,

if I set 	"auto_highlight" : true
my Sidebar is no longer opened.

I open the directory and some files afterwards with the commandline of sublime.

If I disable Autohighlight the Sidebar works normal, but as soon as I enable Autohighlight, this bar isn't displayed anymore:
![auswahl_023](https://user-images.githubusercontent.com/32219087/40650182-f39078ce-6332-11e8-943c-d17d22aaf989.png)

Its this Addon:
https://packagecontrol.io/packages/SideBarEnhancements

**Comment by poucotm** [comment]
Hmm, it is weird. They are not related each other.
