### ISSUE TITLE
setting user didn't work

### ISSUE THREAD

**Issue by jesusslim** [poucotm/Log-Highlight#30]
i copy the whole setting-default to setting-user,and changed every color,but it didn't work.it seems that this package always load default-setting.

Sublime build 3207

Mac OS High Sierra 10.13

my setting-user file：

{
	"severity" : {

		// error __________________________________________________
		"error" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^Error-\\[", "^\\s*[\\n]" ],                      // Error-[ ~ next empty line (multi-line)
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)error", "[\\r\\n]" ],  // a line including case-insensitive 'error' with or without a link in front of 'error'
				[ "^\\w+:\\s*\\*E", "[\\r\\n]" ]                     // ...: *E ... (single line)
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#3b4fff", // error message
				"link"  : "#3b4fff", // link in error message
				"quote" : "#3b4fff"  // quote in error message
			},
			"icon"  : "Danish Royalty/error.png"   // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// warning ________________________________________________
		"warning" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^Warning-\\[", "^\\s*[\\n]" ],                    // Warning-[ ~ next empty line (multi-line)
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)warning", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or without a link in front of 'warning'
				[ "^\\w+:\\s*\\*W", "[\\r\\n]" ]                     // ...: *W ... (single line)
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#3b4fff", // warning message
				"link"  : "#3b4fff", // link in warning message
				"quote" : "#3b4fff"  // quote in warning message
			},
			"icon"  : "Danish Royalty/warning.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// info ___________________________________________________
		"info" : {
			"enable"  : false,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^Information-\\[", "^\\s*[\\n]" ],                // Information-[ ~ next empty line (multi-line)
				[ "^\\[INFO\\]", "[\\r\\n]" ]                        // [INFO] ... (single line)
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#3b4fff", // info message
				"link"  : "#3b4fff", // link in info message
				"quote" : "#3b4fff"  // quote in info message
			},
			"icon"  : "Danish Royalty/info.png"    // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		}
	}
}

**Comment by poucotm** [comment]
Refer to README.

Extensible Severity Levels
You can add, remove, change severity levels like debug/notice/emergency in Log Highlight.sublime-settings, run Log Highlight: Generate Custom Syntax & Theme command. You may have to restart sublime text once.

**Comment by jesusslim** [comment]
> Refer to README.
> 
> Extensible Severity Levels
> You can add, remove, change severity levels like debug/notice/emergency in Log Highlight.sublime-settings, run Log Highlight: Generate Custom Syntax & Theme command. You may have to restart sublime text once.

Oh it works,it's cool.Thx!
