### ISSUE TITLE
the color of style token of sublime text 3 is not as expected

### ISSUE THREAD

**Issue by wuxinxinggg** [poucotm/Log-Highlight#32]
As title described, the style token is not as expected, it is white only of all the style. sublime text build is build 3207

**Comment by poucotm** [comment]
Sorry, I don't get it. What is the style token ? (I'm using 3207 also)

**Comment by wuxinxinggg** [comment]
It should be multiple color, but it is white only in my side.

**Comment by poucotm** [comment]
It is weird. I'm also using 3207.  
![image](https://user-images.githubusercontent.com/19210389/64172014-fd307500-ce8e-11e9-957a-2d12948affe4.png)
Did you run with the default settings or your own ?

**Comment by wuxinxinggg** [comment]
I am using the default setting, the reproduce steps is as following:
1. open a .log file and right click and select log highlight, you will see the error log is red and warming is yellow;
2. select one of the word and right click, select style token->style 1, the word will be solid white, select the other word and with the same steps with style 2, the word would also be solid white, and select another with style 3, it still be solid  white;
3. If you do the same thing as the step 2 in some files log highlight doesn't take effect, such .c/.h/.cpp files, it would be style 1 is one color, style 2 is the other, and style 3 is another;

**Comment by poucotm** [comment]
I didn't know that 'style token' meant other plug-in. It is another plug-in, functionally they can conflict. I didn't care about that plug-in. That plug-in maybe also didn't care about 'log highlight'.
