### ISSUE TITLE
Custom Syntax not dysplaying selected color

### ISSUE THREAD

**Issue by RDLemos** [poucotm/Log-Highlight#33]
Hello,
Great Package!
I have the following issue: I am trying to highlight some specific keywords in my log. I have created a debug entry and selected the colors and icons.
The icon is displayed, and the Summary show the line that matches the expression, but doe not matter what I do, the Log does not show in the color selected ( as in errors).

		// debug ___________________________________________________
		"debug" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]

				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)onMessageReceived:",""], 	// a line including case-insensitive 'onMessageReceived'
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)wakeup", "" ],            // wakeup ... (single line)
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Tap/Button", "" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)isCallActivityVisible", "" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#F94823", // debug message
				"link"  : "#23F9E5", // link in info message
				"quote" : "#F923CB "  // quote in info message
			},
			"icon"  : "Blueberry/bonus.png"    // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		}
![Example log 2019-10-16_16-01-23](https://user-images.githubusercontent.com/3058038/66954367-49460c00-f02e-11e9-9bd1-1ab2de333082.jpg)

**Comment by poucotm** [comment]
I think that you didn't run **`Log Highlight: Generate Custom Syntax & Theme `** command.

**Comment by RDLemos** [comment]
H @poucotm ,
Thanks for the quick reply.
I did run the command and then have tried to run LogHighlight: Erase Custom Syntax & Theme, and Generate again, but I get the same:
I see the custom icons on the left side, and the matching expression shows in the summary but only errors get the colored. 

![Screen Shot 2019-10-18 at 5 23 07 PM](https://user-images.githubusercontent.com/3058038/67129415-995ad500-f1cc-11e9-9de3-597c3cb54603.png)
![Screen Shot 2019-10-18 at 5 22 25 PM](https://user-images.githubusercontent.com/3058038/67129426-9fe94c80-f1cc-11e9-997f-e716534137d4.png)
![Screen Shot 2019-10-18 at 5 21 59 PM](https://user-images.githubusercontent.com/3058038/67129434-a4156a00-f1cc-11e9-85f9-831ad9800f81.png)

**Comment by poucotm** [comment]
![image](https://user-images.githubusercontent.com/19210389/67139500-f5d0f980-f28b-11e9-959f-692ca8233ff7.png)

In my computer, it works well...

**Comment by stk83** [comment]
I have the same issue. sublime version 3.2.2 Build 3211

**Comment by poucotm** [comment]
I also use version 3211 Windows 10.

**Comment by RDLemos** [comment]
@poucotm , I am not sure how or why, but after I completely closed SublimeText3 (I had a reboot in between but I do not think it mattered), the custom logs start showing the color... (??)
Anyway, it is working for me now (screenshot below).
Thanks for the support!

![Screen Shot 2019-10-21 at 9 56 37 PM](https://user-images.githubusercontent.com/3058038/67254968-cc5fcb80-f44d-11e9-846d-72a93ebdf727.png)
