### ISSUE TITLE
icons are not always shown

### ISSUE THREAD

**Issue by gituser823** [poucotm/Log-Highlight#35]
hello,

I love your Addon :)

I have the problem, that the icons are not shown, when I use the Loghighlight-Button from the rightclickmenu of sublime.
The text is parsed fine, but the Icons only appear after I generate the Custom Syntax and Theme.

I just changed something in the config, now the icons show for some reason (I could not determine yet what makes them show and what doesn't), but the part I added shows no icon.
The text is parsed and colored correctly though.

To show the Icons, I sometimes randomly regenerate the Syntax and click to other tabs and change the config and sometimes it works then.
I am using Sublime Text 3.2.2 Build 3211 on Linux Mint 19.1

Edit:
I have set autohighlight to false and always use the button manually and "system" as logtype.

Also a not related request: Can the parsing times be improved? For long files it takes sometiems 20 seconds to parse them.

**Comment by poucotm** [comment]
Hi, @gituser823 
I don't know the reason. Did you test with default error/warning settings ? 
A simple log is tested as below with only default settings. 

![image](https://user-images.githubusercontent.com/19210389/85860639-13326c00-b7fa-11ea-8da0-835a46e220bd.png)

**Comment by gituser823** [comment]
I have now tested it on Windows, the same Problem happens.
With the default configuration it works,
Then I imported my config and it no longer worked.
Here is a Screenshot how it looks:

http://prntscr.com/t6z2o8

My config is

`{

	/*  Configuration  ____________________________________________
	*/

	// enable context menu
	"context_menu": true,

	// Auto Highlight for a log file, build window
	"auto_highlight" : false,

	// log file extension
	"log_ext": [ ".log"  ], // use ".*" for all file extensions - but can not use `Auto Highlight`

	// "compile" - link, summary, bookmark are usable, "system" - only for highlight
	"log_type": "system",

	/*  Options for `compile` type log  ___________________________
	*/

	// use clickable link or not
	"use_link": false,

	// search base directory automatically for relative path
	"search_base": {
		"enable" : true,
		// hidden folders are ignored as default, like .git, .svn
		"ignore_dir" : [""],
		// adjust when using network like samba
		"max_scan_path" : 1000
	},

	// summary panel
	"summary_panel": false,         // show summary panel

	// bookmark
	"bookmark_enable": false,       // enable/disable bookmarks
	"bookmark_goto_error": false,   // automatically go to 1st error line

	/*  Log Syntax, Color scheme  _________________________________
	*/

	// severity level
	"severity" : {


		// yellow info________________________________________________
		"yellow_info" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)none yet", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or without a link in front of 'warning'
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)no other find", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or without a link in front of 'warning'
				[ "^{{{LINK}}}?[^\\r\\n]*? updater: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)hotplugd:", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Hardware Version:", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Diskstationmodel:", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?UPNP Model:", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Serialnumber:", "[\\r\\n]" ],
				[ "^RAM, calced", "[\\r\\n]" ],
				[ "^RAM free.result", "[\\r\\n]" ],
				//[ "(?:RAM)", "^\\s*[\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?[A-Z]([0-9]{1,2})\\:([0-9]{1,2})\\:([0-9]{1,2})(\\+([0-9]{1,2})\\:([0-9]{1,2}))*", "" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF9900", // yellow info message
				"link"  : "#FF9900", // link in yellow info message
				"quote" : "#FF9900"  // quote in ywllow info message
			},
			""  : "Blueberry/tag_yellow.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// error red__________________________________________________
		"error" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Memtest failed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)DRDY ERR", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)invoked oom-killer", "[\\r\\n]" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Call Trace:", "end trace" ],
				//[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Call Trace:", "[\\r\\n]" ],
				[ "[^\\r\\n]*?(?i)Call Trace:", "^\\s*[\\n] | (end trace).*?[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)ext4-fs error", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?JBD2: Error", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Reallocated_Sector_Ct: ([1-9]{1,12})", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Current_Pending_Sector: ([1-9]{1,12})", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Offline_Uncorrectable: ([1-9]{1,12})", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?found ([1-9]{1,12}) (dropped|bugged) Packages", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ata([0-9]{1,2})\\.([0-9]{1,4})\\: exception", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Speed: 10[0]{0,1}Mb/s", "[\\r\\n]" ],
				[ "^smart.*?:*?\\(incompatible\\)", "[\\:]" ],
				[ "^sd.*?:*?\\(incompatible\\)", "[\\:]" ],
				[ "Completed\\: read failure", "[\\,]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Mountpoints more than 90% full: \\(([1-9])\\)", "^\\s*[\\n]" ],
				[ "^Known Issue", "^\\s*[\\n]" ],
				[ "^CPU or Disk is overheating:", "^\\s*[\\n]" ],
				[ "[^\\r\\n]*?has 16 Terabyte Volume Limitation", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF0000", // error message
				"link"  : "#E6DB74", // link in error message
				"quote" : "#4F99D3"  // quote in error message
			},
			"icon"  : "Danish Royalty/error.png"   // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// error light red________________________________________________
		"lighterror" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]

				//[ "^{{{LINK}}}?[^\\r\\n]*?Drittanbieterpakete:", "^\\s*[\\n]" ],
				[ "^No Volumes mounted.", "[\\r\\n]" ],
				[ "^available Updates*", "^\\s*[\\n]" ],
				[ "^Last Extended SMART-Test: never", "[\\,]" ],
				[ "^smart.*?:*?\\(not listed\\)", "[\\:]" ],
				[ "Interrupted \\(host reset\\)", "[\\,]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?More current DSM Version available.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?IPv6 on", "[\\r\\n]" ],
				[ "^Update available for ", "[\\r\\n]" ],
				//[ "PowerOnHours: \\b(1[0-9]|2[0-4])[0-9]{3}\\b", "[\\r\\n]" ],
				[ "PowerOnHours: ((2[5-9]|[3-9][0-9])[0-9]{3}|[1-9][0-9]{5})", "[\\r\\n]" ],
				[ "^More RAM installed!", "[\\r\\n]" ],
				[ "(Samba|NFS|AFP) is off", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF7F7F", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			""  : "" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// error light red with warning icon_____________________________________________
		"lighterror" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]

				//[ "^{{{LINK}}}?[^\\r\\n]*?Drittanbieterpakete:", "^\\s*[\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?No Memory tests have been run.", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF7F7F", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			"icon"  : "Blueberry/warning.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},
		// generic error VERY LIGHT red________________________________________________
		"verylighterror" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)failed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)fail", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?\\[(?i)error\\]", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)disabled", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)warning", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?\\[err\\]", "[\\r\\n]" ],
			],
			"color" : {
				"base"  : "#FF9F9F", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			""  : "" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},
		// okay green________________________________________________
		"warning" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^\\w+:\\s*\\*W", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*? is ok!!", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Successfully started ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?finished boot up", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?enabled", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Memtest passed!", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?[0-9]{0,6} Memory tests have passed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Success to update", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)Startup successful", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?all service finish boot up", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?No full \\(\\>90%\\) Mountpoints found.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Reallocated_Sector_Ct: ([0]{1})", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Current_Pending_Sector: ([0]{1})", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Offline_Uncorrectable: ([0]{1})", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?found 0 (dropped|bugged) Packages in ifconfig.result.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?DSM Version is latest!", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Mountpoints more than 90% full: \\(0\\)", "[\\r\\n]" ],
				[ "PowerOnHours: \\b([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])\\b", "[\\r\\n]" ],
				[ "^smart.*?:*?\\(compatible\\)", "[\\:]" ],
				[ "^sd.*?:*?\\(compatible\\)", "[\\:]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?IPv6 off", "[\\r\\n]" ],
				[ "^Last Extended SMART-Test: ([0-9]{1,6})", "[\\,]" ],
				[ "Completed without error", "[\\,]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?No Third Party Packages found.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Speed: [1-2][0]{3,5}Mb/s", "[\\r\\n]" ],
				[ "^same RAM installed as preinstalled!", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(Third Party packages|Ext4-/Btrfs-Errs|improper shutdowns|Volume crashes|degraded volumes|generic errs|DRDY|Database is malformed|Out of Memory kills|generic crashes|Call Traces):\t*?none", "[\\r\\n]" ],
				[ "(Samba|NFS|AFP) is on", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#A1B347", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			"icon"  : "Blueberry/info.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// Spaces/Volume purple________________________________________________
		"spaces" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?tool.shared", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#8af2fb", // warning message
				"link"  : "#8af2fb", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			""  : "" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// kernel blue________________________________________________
		"kernel" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "(\\S{1,})\\s([A-Za-z]{1,18})*?\\:*?\\s*?\\[\\s*?([0-9]{1,8})\\.[0-9]{6}", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#33B5E5", // warning message
				"link"  : "#FD971F", // link in warning message
				"quote" : "#4F99D3"  // quote in warning message
			},
			""  : "" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		/*// to be decided________________________________________________
		"dark_blue" : {
			"enable"  : true,
			"summary" : true,
			"pattern" : [
				[ "^{{{LINK}}}?[^\\r\\n]*?img_backup: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*? upsmon", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*? upsd", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?root: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?updater-svr: ", "[\\r\\n]" ],
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#9d15f6", // yellow info message
				"link"  : "#9d15f6", // link in yellow info message
				"quote" : "#9d15f6"  // quote in ywllow info message
			},
			"icon"  : "Danish Royalty/warning.png" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},*/

		// to ignore grey ________________________________________________
		"greyed" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)link is slow to respond, please be patient", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)wake up successful, the reset fail can be ignored", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)wake up from deepsleep, reset link now", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)times, suppressed by syslog-ng on", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)device unplugged sstatus", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)resource_api.cpp:163 Acquire", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i)resource_api.cpp:163 Acquire", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(?i) is not ssd", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?] info cache generated", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?System isn't ready, so cannot get scemd status.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?thumbd: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?RCClean succeeded", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?root: Check device busy: passed", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?mkcert: Verifying certificate in", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?scanner.c:([0-9]{1,4}) skip counting", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?DDNS Expired. UpdateAll.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?DDNS got IP changed. UpdateAll.", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?not factory enviroment, finish manutild", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?device plugged sstatus", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?Speed: Unknown\\!", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?status unknown", "[\\r\\n]" ],
				[ "^No QuickConnect alias is set", "[\\r\\n]" ],
				[ "^LUN-Config-file is empty.", "[\\r\\n]" ],

				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#71878F", // greyed out message
				"link"  : "#71878F", // link in grey message
				"quote" : "#71878F"  // quote in grey message
			},
			""  : "" // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		},

		// orange network ___________________________________________________
		"network" : {
			"enable"  : true,
			"summary" : false,
			"pattern" : [
				// [ "begin regex", "end regex" ] or [ "match regex", "" ]
				[ "^{{{LINK}}}?[^\\r\\n]*?dhcp-client: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?dns_config_change", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?interface-catcher: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?(ipv6_change|ipv4_change|hostname_change|if_link_up|if_link_down|dns_change|gateway_change) hook event", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?gateway_config_change hook event: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?dhcp-client6: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?dhclient: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?rc.network: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ipsec_", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?openvpn\\[([0-9]{1,6})\\]", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ddnsd: ", "[\\r\\n]" ],
				[ "^{{{LINK}}}?[^\\r\\n]*?ntpd", "[\\r\\n]" ]
				// <-- Remove, Change, Add More Patterns Here -->
			],
			"color" : {
				"base"  : "#FF8E5A", // info message
				"link"  : "#b36915", // link in info message
				"quote" : "#428a99"  // quote in info message
			},
			"icon"  : "Blueberry/tag_orange.png"    // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
		}, //,?

		// <-- Remove, Change, Add More Severity Level Here -->
	},

	// theme color set
	"theme_color": {
		"background"      : "#161C23",
		"foreground"      : "#D7D7D7",
		"caret"           : "#F29718",
		"selection"       : "#3A5166",
		"selectionBorder" : "#181E26",
		"lineHighlight"   : "#283240",
		"summary_title"   : "#D7D7D7"
	}

}
`

**Comment by poucotm** [comment]
As commented in the settings,
`// "compile" - link, summary, bookmark are usable, "system" - only for highlight`
Icons can not be seen in the "system" type. Icons are added within bookmark processing.

**Comment by gituser823** [comment]
Oh right, sorry for opening the bug...
Can I turn this Bugreport into a feature request then?

**Comment by poucotm** [comment]
If you want to display icons, you shall change the log type as "compile"
and turn off summary panel. But bookmark process makes more slow. You may
not want it


2020년 6월 27일 (토) 오후 5:33, gituser823 <notifications@github.com>님이 작성:

**Comment by gituser823** [comment]
So I have the same setting of "system" at work.
Usually here it does not show the Icons.
But I changed something in the File, then it loaded for a few seconds and all of a sudden the Icons appeared.
Do you know what has caused this and can I make this "bug" somehow permanent?
I did not change anything in the loghighlight config or generated the Syntax.

**Comment by poucotm** [comment]
@gituser823 , As I stated for your early issue, it supports multiple kinds of logs now.
