### ISSUE TITLE
Change highlighted text background color

### ISSUE THREAD

**Issue by eandmsz** [poucotm/Log-Highlight#36]
Hi,

 I would like to have red background color for the highlighted errors instead of coloring the font itself, so it becomes even more visible when scrolling through thousands of lines.
 Is it possible to configure the text background color somehow?

**Comment by poucotm** [comment]
@eandmsz , I've updated for it (v1.10.0), you can set theme in settings :
```
"color" : { // "foreground" or ["foreground", "background"]
	"base"  : ["#70991f", ""], // info message
	"link"  : ["#b36915", ""], // link in info message
	"quote" : ["#428a99", ""], // quote in info message
},
```

**Comment by eandmsz** [comment]
Great, thanks!

**Comment by eandmsz** [comment]
I think you forgot to update the theme colors in the default config, which makes it all white background if the user does not have their own theme colors in the user config.

**Comment by poucotm** [comment]
Did you see white background ? I deleted the background setting on purpose. As changed, it sets the background automatically getting from current color-scheme. If you don't set color-scheme, sublime sets as default color-scheme : 'Monokai.sublime-color-scheme'.

**Comment by eandmsz** [comment]
Ah, it was a bracketing or comma error in my user configuration that caused this. I don't even know how it could happen as it gets validated when you save the config, so I cannot reproduce it now.

Thans, it works great.
