### ISSUE TITLE
didn't work after upgrade today

### ISSUE THREAD

**Issue by jesusslim** [poucotm/Log-Highlight#37]

**Comment by poucotm** [comment]
Did you migrate settings as like this ?

https://github.com/poucotm/Log-Highlight/blob/master/Log%20Highlight.sublime-settings

**Comment by jesusslim** [comment]
> Did you migrate settings as like this ?
> 
> https://github.com/poucotm/Log-Highlight/blob/master/Log%20Highlight.sublime-settings

Oh it works.Thank you very much.It's cool.
