### ISSUE TITLE
Wildcards no longer working for extension

### ISSUE THREAD

**Issue by eandmsz** [poucotm/Log-Highlight#38]
Hi,

 It seems wildcards are no longer working for specifying extensions since v2.0.0.

 I would like to have the option to have something like:
**"extension"    : [ "messages.*" ],**

 P.S.: Sometimes there are generated filenames, so it's important to have and it's not just about covering the log rotation: messages.1, messages.2, etc.

**Comment by eandmsz** [comment]
One more thing I noticed is that it doesn't like uppercase letters in filenames either.
For example it can match: "**vm11-pl-4**" but it cannot match "**vm11-PL-4**"

**Comment by poucotm** [comment]
@eandmsz , I've updated to add wildcard for extension. About case-sensitivity, it makes filenames lowercase before comparing. I think it is good for Windows users.

**Comment by eandmsz** [comment]
@poucotm I have updated to 2.0.2.
If someone specifies "MESSAGES" in the config it will **not** match the filename "MESSAGES" because the filename gets converted to lowercase, but the pattern does not.
I think  to make it properly case-insensitive you need to convert the patterns to lowercase as well. And maybe it worth mentioning in the comments that the matching is case-insensitive.

Regarding the wildcard: I'm not sure what I'm doing wrong but neither "messages*" nor "messages.*" pattern matches the filename "messages.1" for me.

**Comment by poucotm** [comment]
@eandmsz, it works in my test as below (Windows 10).

`"extension"    : [ "messages.*" ], // case-insensitive`

![image](https://user-images.githubusercontent.com/19210389/87437562-74937100-c629-11ea-9de2-b0abbf21c18d.png)

**Comment by eandmsz** [comment]
I'm also on Windows 10.
Okay now it works, I have no idea what made this error, but I have uninstalled/reinstalled all the plugins I had (FilterLines, SortBy, Log Highlight) and found that I had the "summary" : true, still left from 1.x.x config, so I removed that.

Thanks
