### ISSUE TITLE
Log-Highlight does not work

### ISSUE THREAD

**Issue by NinjaMooseWMD** [poucotm/Log-Highlight#39]
I have a Macbook Pro with a fresh install of Sublime Text 3. I used Package Control to install log highlight.  I've opened log files and tried to apply the Log Highlight syntax via the context menu and via the command palette. It does not highlight errors in red. It does not provide the window at the bottom of the screen with a summary of all errors. I don't see any indication that it is working at all. It was working for me a few months ago but it isn't anymore. Any suggestions?

Sometimes I get the following in the console:

LOG HIGHLIGHT : ERROR _______________________________________
Traceback (most recent call last):
  File "/Users/mikemoose/Library/Application Support/Sublime Text 3/Installed Packages/Log Highlight.sublime-package/Log Highlight.py", line 649, in run
    self.run_imp()
  File "/Users/mikemoose/Library/Application Support/Sublime Text 3/Installed Packages/Log Highlight.sublime-package/Log Highlight.py", line 688, in run_imp
    set_syntax_theme(self.view, lname)
  File "/Users/mikemoose/Library/Application Support/Sublime Text 3/Installed Packages/Log Highlight.sublime-package/Log Highlight.py", line 194, in set_syntax_theme
    tree = plistlib.readPlist(ctheme)
  File "./python3.3/plistlib.py", line 73, in readPlist
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mikemoose/Library/Application Support/Sublime Text 3/Packages/Log Highlight/Log Highlight.tmTheme'
=============================================================

**Comment by NinjaMooseWMD** [comment]
I just downloaded all of the files manually and placed them in ~/Application Support/Sublime Text 3/Packages/Log Highlight/ and I now get some syntax coloring. I still do not get the summary window. Also, when I use the Command Palette to Highlight Error/Warning I get an error that disappears to quickly to read but it something along the lines of Unable to find Base Directory.

**Comment by poucotm** [comment]
@NinjaMooseWMD, Did you migrate settings ? And run `Log Highlight Generate Syntax & Theme` ? 

https://github.com/poucotm/Log-Highlight/blob/master/Log%20Highlight.sublime-settings

**Comment by thebishopgame** [comment]
I'm also having this issue, I was using LH for builds and they seem to have just stopped highlighting all of a sudden. Tried re-installing and have tried moving stuff around as NinjaMooseWMD has suggested. Also tried setting "syntax": "Packages\/User\/Log Highlight.tmLanguage", in my .sublime-build but no go.

**Comment by poucotm** [comment]
@thebishopgame `Packages/User/Log Highlight.tmLanguage` is old. If you run `Log Highlight Generate Syntax & Theme` with your settings, new .tmLanguage, .tmTheme will be made in `Packages\User\Log Highlight`.
e.g.) if you set the name "cpp" like below, cpp-log.tmLanguage, cpp-log.tmTheme will be generated.
```
"log_list" : {
   "cpp" :
      { "type" : "compile", ...
```

**Comment by NinjaMooseWMD** [comment]
> @NinjaMooseWMD, Did you migrate settings ? And run `Log Highlight Generate Syntax & Theme` ?
> 
> https://github.com/poucotm/Log-Highlight/blob/master/Log%20Highlight.sublime-settings

What do you mean by migrate settings? I'm a n00b here. :-)

**Comment by thebishopgame** [comment]
@poucotm, No go. I've updated my settings to fit the new settings format (i.e. moved my severity and theme settings into the log list, removed the summary entries, removed the deprecated settings, generated the tmLanguage and tmTheme as you said, and set the tmLanguage as my syntax in the build system, still nothing.

**Comment by poucotm** [comment]
@thebishopgame Pls, share your settings.

**Comment by thebishopgame** [comment]
@poucotm Here you go, sorry if there's a better way to post this in github that I don't know about, I'm not here much.

```
{
    // enable context menu
    "context_menu": true,

    // Auto Highlight for a log file, build window
    "auto_highlight" : true,

    // Output panel list for Auto Highlight
    "auto_highlight_output_panel": ["exec"], // exec = build

    // bookmark
    "bookmark_enable": true,       // enable/disable bookmarks
    "bookmark_goto_error": true,    // automatically go to 1st error line

    "log_list" : {

        "c" :
        {
            "type"         : "compile", // "compile" - link, bookmark (icon) are usable, "system" - only for highlight
            "extension"    : [ "*.log", ".vcs.log", ".cpp.log", "log*", ".c.log" ],
            "output.panel" : [ "exec" ], // exec - to apply to build results
            "use_link"     : true,
            "search_base": {
                "enable"        : true, // false : when using absolute path
                "ignore_dir"    : [""], // hidden folders are ignored as default, like .git, .svn
                "max_scan_path" : 1000,
            },
            "bookmark" : {
                "enable"     : true, // false : do not display icons too
                "goto_error" : true, // automatically goto 1st error line
            },
            // severity level
            "severity" : {

                // error __________________________________________________
                "error" : {
                    "enable"  : true,
                    "pattern" : [
                        // [ "begin regex", "end regex" ] or [ "match regex", "" ]
                        [ "^Error-\\[", "^\\s*[\\n]" ],                      // Error-[ ~ next empty line (multi-line)
                        [ "^{{{LINK}}}?[^\\r\\n]*?error:", "[\\r\\n]" ],  // a line including case-insensitive 'error' with or without a link in front of 'error'
                        [ "^\\w+:\\s*\\*E", "[\\r\\n]" ],                     // ...: *E ... (single line)
                        [ "^{{{LINK}}}?[^\\r\\n]*?undefined", "[\\r\\n]" ],  // a line including case-insensitive 'error' with or without a link in front of 'error'
                        // <-- Remove, Change, Add More Patterns Here -->
                    ],
                    "color" : {
                        "base"  : "#F92672", // error message
                        "link"  : "#E6DB74", // link in error message
                        "quote" : "#4F99D3",  // quote in error message
                    },
                    "icon"  : "Danish Royalty/error.png",   // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
                },

                // warning ________________________________________________
                "warning" : {
                    "enable"  : true,
                    "pattern" : [
                        // [ "begin regex", "end regex" ] or [ "match regex", "" ]
                        [ "^Warning-\\[", "^\\s*[\\n]" ],                    // Warning-[ ~ next empty line (multi-line)
                        [ "^{{{LINK}}}?[^\\r\\n]*?(?i)warning", "[\\r\\n]" ],// a line including case-insensitive 'warning' with or with  a link in front of 'warning'
                        [ "^\\w+:\\s*\\*W", "[\\r\\n]" ]                     // ...: *W ... (single line)
                        // <-- Remove, Change, Add More Patterns Here -->
                    ],
                    "color" : {
                        "base"  : "#FAD7A0", // warning message
                        "link"  : "#FD971F", // link in warning message
                        "quote" : "#4F99D3",  // quote in warning message
                    },
                    "icon"  : "Danish Royalty/warning.png", // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
                },

                // info ___________________________________________________
                "info" : {
                    "enable"  : true,
                    "pattern" : [
                        // [ "begin regex", "end regex" ] or [ "match regex", "" ]
                        [ "^Information-\\[", "^\\s*[\\n]" ],                // Information-[ ~ next empty line (multi-line)
                        [ "^\\[INFO\\]", "[\\r\\n]" ],                       // [INFO] ... (single line)
                        // <-- Remove, Change, Add More Patterns Here -->
                        [ "^{{{LINK}}}?[^\\r\\n]*?(?i)note:", "[\\r\\n]" ],  // a line including case-insensitive 'warning' with or without a link in front of 'warning'
                        [ "^ \\S", "[\\r\\n]"]
                    ],
                    "color" : {
                        "base"  : "#D7D7D7", // info message
                        "link"  : "#D7D7D7", // link in info message
                        "quote" : "#428a99",  // quote in info message
                    },
                    "icon"  : "Danish Royalty/info.png",    // remove "icon" not to use icon, "dot", "circle" "bookmark" are possible
                },

                "file" : {
                    "enable"  : true,
                    "pattern" : [
                        [ "^  CC", "[\\r\\n]"]
                    ],
                    "color" : {
                        "base"  : "#797D7F", // info message
                    },
                },
                // <-- Remove, Change, Add More Severity Level Here -->
            },

            // theme color set
            "theme": {
                "background"      : "#161C23",
                "foreground"      : "#D7D7D7",
                "caret"           : "#F29718",
                "selection"       : "#3A5166",
                "selectionBorder" : "#181E26",
                "lineHighlight"   : "#283240",
            },
        },
        // <-- remove, change, add more log list here -->
    },
}


```

**Comment by poucotm** [comment]
@thebishopgame, I've updated to fix up the codes getting colors from settings (v2.0.3).

This is picture with your settings.
![image](https://user-images.githubusercontent.com/19210389/87841178-733e9e80-c8de-11ea-8131-c4fcd8094cb0.png)

And you don't need to use all examples.
`"extension"    : [ "*.log", ".vcs.log", ".cpp.log", "log*", ".c.log" ],`
```
[ "^Error-\\[", "^\\s*[\\n]" ], // Error-[ ~ next empty line (multi-line)
[ "^{{{LINK}}}?[^\\r\\n]*?error:", "[\\r\\n]" ],  // a line including case-insensitive 'error' with or without a link in front of 'error'
[ "^\\w+:\\s*\\*E", "[\\r\\n]" ],                     // ...: *E ... (single line)
```

**Comment by poucotm** [comment]
@NinjaMooseWMD, Are you using your own settings ? or just running with example settings ?

**Comment by thebishopgame** [comment]
@poucotm, Fantastic! Do you know about how long that'll take to propagate to the package manager?

**Comment by poucotm** [comment]
@thebishopgame , about 2 or 3 hours. Instead of waiting, you can change your settings like this. The 2nd column is for background color.
```
"color" : {
   "base"  : ["#F92672", ""], // error message
   "link"  : ["#E6DB74", ""], // link in error message
   "quote" : ["#4F99D3", ""],  // quote in error message
},
```

**Comment by thebishopgame** [comment]
Whoo, my colors are back! Thank you so much!
