### ISSUE TITLE
No auto highlight and no summary 

### ISSUE THREAD

**Issue by KlayaR** [poucotm/Log-Highlight#40]
Hello.

I reinstalled windows. So I reinstalled ST3 and your awesome plugin. But it doesn't auto highlight and doesn't show summary like it used to =( I didn't change any settings

**Comment by poucotm** [comment]
@KlayaR , To support multiple log types, the settings are chagned. Please, change your settings like this : https://github.com/poucotm/Log-Highlight/blob/master/Log%20Highlight.sublime-settings
And summary panel has been deprecated.

**Comment by KlayaR** [comment]
It didn't change anything with those configs

**Comment by poucotm** [comment]
Are you sure that your user settings look like this ?
```
	"log_list" : {
		"example" : // specify name as yours
		{
			"type"         : "compile", // "compile" - link, bookmark (icon) are usable, "system" - only for highlight
			"extension"    : [ "*.log", ".vcs.log", ".cp
```

**Comment by KlayaR** [comment]
I copied/pasted the exact settings that you sent

**Comment by poucotm** [comment]
Did you see any error messages on sublime console (ctrl + `) ?

**Comment by KlayaR** [comment]
unable to auto detect encoding for C:\Users\Klayar\Desktop\2020-04-16-3.log, using fallback encoding Western (Windows 1252)

**Comment by KlayaR** [comment]
So it's ST3 who doesn't see a .log file as a log file?

**Comment by poucotm** [comment]
It doesn't look like the cause.
![image](https://user-images.githubusercontent.com/19210389/87874301-b8a8bc00-ca03-11ea-86d9-2e55c72fb9d4.png)
