### ISSUE TITLE
config broken after update

### ISSUE THREAD

**Issue by gituser823** [poucotm/Log-Highlight#41]
hello,

Sublime installed the latest Version 2.0.7 of your Addon and now my Script no longer works.

What can I do to fix this?
Do I need to change anything in my configfile after the updates?
If I see it correctly, it seems to use the standard predefined configfile now.

While we're at it, can you also give me an example how I can define multiple configs for different extensions now, which you added with one of the last updates?

Thanks.

**Comment by poucotm** [comment]
Please check the previous issue        https://github.com/poucotm/Log-Highlight/issues/37

**Comment by tablatronix** [comment]
I replaced the settings with the new and it still doesn't work.
