### ISSUE TITLE
Generate syntax with random result

### ISSUE THREAD

**Issue by SteffenWa** [poucotm/Log-Highlight#43]
Hello,

I recently wondered why little changes (like a simple color change) to my settings very often result in Log-Highlight not working as expected.
Workflow: change user settings -> generate syntax -> close ST3 -> open ST3 -> apply Log-Highlighting
Now I made several consecutive "generate syntax" while leaving the settings file **identical**.
Big surprise: tmTheme is generated completely different (see attachment, all files generated from also attached settings file!?). In the working version, there is proper line formatting, while it is missing in the non-working tmTheme. Instead there are several commented lines there which do not appear in the working version.
[settings.zip](https://github.com/poucotm/Log-Highlight/files/5164426/settings.zip)

I am working on Win10, ST3.2.2, Build3211, Log-Highlight 2.0.9

Update:
It seems that the tmTheme is updated when ST3/LogHighlight first matches a file with the respective extension pattern of this log-highlight profile when the file is opened. After this, the tmTheme changed to the working version.
Instead, when the file to highlight is already open and "Select syntax ...hnf" or just "highlight" is issued, the tmTheme does not get updated/corrected.
The initial (not working) version is easily identifiable by the second line:
`<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`
In the corrected version this line is changed to 
`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`

**Comment by poucotm** [comment]
@SteffenWa , Hi,
A .tmTheme file can be changed when applying its background color as current color-scheme. Although two files look different, they shall have the same elements except commented. I don't know why one is working, and the other is not working. However, I've updated the package (v2.0.10) to generate .tmTheme similarly.

And, in your settings, I recommend that you should delete 'example' because it has the same extension with 'hnflog'.
```
'hnflog' : { "extension" : [ ".log", ... ],
'example' : { "extension" : [ "*.log", ".vcs.log", ".cpp.log", ... ],
```
