### ISSUE TITLE
Nothing working, context menu doesn't work

### ISSUE THREAD

**Issue by tablatronix** [poucotm/Log-Highlight#44]
I cannot get anything to work the way it was before update.

Right click context `Log highlight` does nothing, changing syntax to Log highlight also does nothing.

![Screen Shot 2020-10-17 at 11 59 26 AM](https://user-images.githubusercontent.com/807787/96348686-3b2b3100-1070-11eb-9157-507c39588bde.png)

I have replaced settings with new default, I have rebuilt syntax,colors

**Comment by tablatronix** [comment]
It seems that fille matches work, unsaved or buffer console windows do not..

![Screen Shot 2020-10-17 at 12 12 21 PM](https://user-images.githubusercontent.com/807787/96348961-159f2700-1072-11eb-93d0-187e05c2a5cb.png)

I also noticed the context menu is sometimes missing...

![Screen Shot 2020-10-17 at 12 16 39 PM](https://user-images.githubusercontent.com/807787/96349050-ab3ab680-1072-11eb-8e18-2f515086c43e.png)

**Comment by tablatronix** [comment]
Open file, change syntax - NOT WORKING
Context Menu - NOT WORKING
open file match - WORKING

I also see 2 syntax sometimes...

![Screen Shot 2020-10-17 at 12 18 07 PM](https://user-images.githubusercontent.com/807787/96349117-08366c80-1073-11eb-810c-a951b3c4bf51.png)

**Comment by tablatronix** [comment]
I have been trying to debug this, but I cannot find anything, I don't even understand what this is supposed to be doing..
	`{ "command": "log_highlight", "caption": "Log Highlight" }`

I see nothing happening

**Comment by tablatronix** [comment]
ok found it, 

```py
            if not lname:
                return
```

**Comment by tablatronix** [comment]
```
LogHighlightCommand run
get_log_name
[ Deviot 2.3.0.dev13 ] Serial Monitor | /dev/cu.SLAB_USBtoUART
Still None
LogHighlightCommand not lname
```

**Comment by tablatronix** [comment]
It works, I had to add an extensionless wildcard..

I assume this is because there are presets so it has to find which preset matches , which is fine i guess, but I think the context menu should always force something.. maybe the first one?

**Comment by poucotm** [comment]
@tablatronix ,
".*" extension was deprecated, when the package was updated to enable multiple log types. You can define multiple log types with different log extensions like this :
```
"log_list" : {
   "abc" :  {
      "extension"    : [ ".abc" ],
      "output.panel" : [ "exec" ], // exec - to apply to build results
      ...
   "def" :  {
      "extension"    : [ ".def" ],
      ...
```
The extensions are used to distinguish log types. In order to use the output panel like 'build' window, you can set `"output.panel" : [ "exec" ]` for a specific log type.

**Comment by tablatronix** [comment]
I use a plugin that generates output panels in view with names like

'[ Deviot 2.3.0.dev13 ] Serial Monitor | /dev/cu.SLAB_USBtoUART'

Is there a way to target these, without using '*' ?

**Comment by poucotm** [comment]
@tablatronix , It looks a just view not a output panel. Anyway, you can add an extension item for it. I've updated the package as v2.1.0.
```
"extension"    : [ ".log", "*.csv", "[ Deviot*" ],
```
![image](https://user-images.githubusercontent.com/19210389/96458899-6d998180-125c-11eb-956a-0593529e1d0d.png)

**Comment by tablatronix** [comment]
Perfect

**Comment by poucotm** [comment]
@tablatronix 
I've updated the package as v2.2.0 to apply 'auto_highlight' correctly for a newly generated view like yours.
You may don't need to run 'Log Highlight' manually if 'auto_highlight' is on.

**Comment by tablatronix** [comment]
I will test it out
