### ISSUE TITLE
Log Highlight causing problems with Goto Anything

### ISSUE THREAD

**Issue by parejkoj** [poucotm/Log-Highlight#45]
When I try to open a file with `Goto Anything...` with Log Highlight installed and there is a file matching the log regex (in my case, just `*.log`) at the top of the list, Goto Anything immediately closes (without opening anything) and this error shows up on the SublimeText console:

```
=============================================================
LOG HIGHLIGHT : ERROR _______________________________________
Traceback (most recent call last):
  File "/Users/parejkoj/Library/Application Support/Sublime Text 3/Installed Packages/Log Highlight.sublime-package/Log Highlight.py", line 269, in fread
    with open(fname, "r") as f:
TypeError: invalid file: None
=============================================================
```

I tried updating my config to reflect the new sublime-settings format, and also just removing all the "Log Highlight" files I could find in my `Sublime/Packages` directory after removing the `Log Highlight` and then reinstalling it, and restarting SublimeText but this is still occurring.

I can still directly open log files with File->Open or using the `subl` commandline.

**Comment by poucotm** [comment]
@parejkoj , I fixed up some codes related with it. Could you try it (v2.2.1) ?

**Comment by parejkoj** [comment]
Thank you, that fixed it!
