### ISSUE TITLE
Disable double click to open link 

### ISSUE THREAD

**Issue by TommyTheBlackbird** [poucotm/Log-Highlight#6]
Is possible to disable the double click to open link. In many log files types there's no such links and I use to double click to select full words for copy and paste.

May be a new setting can be added to disable this feature.

Greets.

**Comment by poucotm** [comment]
Hi, I added `use_link` option to control link on/off. check up v1.2.0. use
it well ~



2017-05-29 21:33 GMT+09:00 TommyTheBlackbird <notifications@github.com>:

**Comment by TommyTheBlackbird** [comment]
Is it a global setting o per severity basis? I'm trying 1.2.0 right now with `use_link: false` but it still opens a new tab when a link is detected in the same line.

Thanks.

**Comment by poucotm** [comment]
Did you try to close log file and sublime and re-open it ?


2017-05-29 23:42 GMT+09:00 TommyTheBlackbird <notifications@github.com>:

**Comment by TommyTheBlackbird** [comment]
Closing and re-opening worked :thumbsup:
