### ISSUE TITLE
Read latest errors on refresh

### ISSUE THREAD

**Issue by superjunky** [poucotm/Log-Highlight#9]
Hi,

I'm loving this package! So I feel I have to apologise for the following question;

- How can I make sure to view the latest errors (usually at the bottom of the log file) on auto-refresh?
Am I using it the wrong way? I cannot find any info on this topic...which make me suspect it's basic common knowledge ;)

- Also, Is there a way to change the linking format, so it catches my custom format:
`/some/path/class-ps-booking-controller.php on line 11`

**Comment by pouco26** [comment]
Hi,
- When the log file is reloaded, the summary view also will be updated, if you did not close the log file.
- The package has been updated for that kind of link expression (v1.8.2).

**Comment by superjunky** [comment]
Nice, thanks! I appreciate it.
